name: hearted_map
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
 

  flutter:
    sdk: flutter
  pull_to_refresh: ^2.0.0
  video_player: ^2.6.1
  get: ^4.6.6
  google_fonts:
  percent_indicator: ^4.2.3
  flutter_slidable: ^3.0.1
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  animated_splash_screen: ^1.3.0
  http: 
  animated_bottom_navigation_bar: ^1.3.3
  web_socket_channel: ^2.4.4
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/map_piece/
    - images/homescreen/
    - images/homescreen/ilands/
    - images/homescreen/cards/
  fonts:
    - family: Himalaya
      fonts: 
        - asset: fonts/Microsoft-Himalaya.ttf
    